version: '3.8'

services:
  db:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: 2fa_db
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U root -d 2fa_db"]
        interval: 1s
        retries: 5
        timeout: 1s
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  2fa:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
      - 2fa
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  test:
    build: .
    command: pytest
    profiles:
      - test
    depends_on:
      - db
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=testing
      - PYTHONPATH=/app
